project:
  type: website
  output-dir: _output

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: false
    
website:
  title: "Species profiles"
  navbar:
    left:
      - href: index.html
      - app.qmd